### PR TITLE
Closes #287: fixes signed builds crashing when opening any website

### LINKED ISSUE #287: Autograph signed builds crash when opening any website
## Steps to reproduce
- Build master
- Sign using `tools/sign_release.sh`
- Deploy code
- Open any website

### Expected behavior
- Website loads

### Actual behavior
- App crashes

### Device information
* Echo Show device: 2nd gen & Show 5
* Latest affected Firefox version: 0a6782925c93e326f1a34dc544a4a445bb1786be (current master)
* Earliest affected Firefox version: ?

### Crash log
```
07-03 14:52:06.533 17648-17648/org.mozilla.connect.firefox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.connect.firefox, PID: 17648
    java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
        at kotlinx.coroutines.MissingMainCoroutineDispatcher.missing(Dispatchers.kt:123)
        at kotlinx.coroutines.MissingMainCoroutineDispatcher.dispatch(Dispatchers.kt:116)
        at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:282)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:23)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:160)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at org.mozilla.focus.toolbar.ProgressBarController.hideProgressBar(ProgressBarController.kt:62)
        at org.mozilla.focus.toolbar.ProgressBarController.onLoadingUpdate(ProgressBarController.kt:28)
        at org.mozilla.focus.toolbar.ToolbarIntegration$setup$3.invoke(ToolbarIntegration.kt:115)
        at org.mozilla.focus.toolbar.ToolbarIntegration$setup$3.invoke(ToolbarIntegration.kt:68)
        at org.mozilla.focus.MainActivity.onSessionLoadingUpdate(MainActivity.kt:193)
        at org.mozilla.focus.browser.BrowserFragment$SessionLoadingObserver.onChanged(BrowserFragment.kt:227)
        at org.mozilla.focus.browser.BrowserFragment$SessionLoadingObserver.onChanged(BrowserFragment.kt:224)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
        at org.mozilla.focus.architecture.NonNullLiveData.setValue(NonNullLiveData.kt:40)
        at org.mozilla.focus.architecture.NonNullMutableLiveData.setValue(NonNullMutableLiveData.kt:19)
        at org.mozilla.focus.session.Session.setLoading(Session.java:80)
        at org.mozilla.focus.session.SessionCallbackProxy.onPageFinished(SessionCallbackProxy.java:39)
        at org.mozilla.focus.webview.FocusWebViewClient.onPageFinished(FocusWebViewClient.java:212)
        at com.amazon.webview.awvclients.AmazonWebViewClient.onPageFinished(AmazonWebViewClient.java:95)
        at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:546)
        at com.android.webview.chromium.WebViewExtAmazonContentsClientAdapter.onPageFinished(WebViewExtAmazonContentsClientAdapter.java:18)
        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:201)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5597)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

### Notes
- [According to this link](https://www.gitmemory.com/issue/Kotlin/kotlinx.coroutines/983/492378969), this can happen when the APKs META-INF folder is modified during the signing process
- Inspecting the META-INF folder of a local build, it contains a lot of AndroidX related files that are not found in our Autograph signed version
- We migrated to AndroidX since our last release (which was successfully signed with Autograph)

### PR DESCRIPTION
**Pull request by Baron-Severin**
### Pull Request checklist

- [ ] This PR includes thorough **tests** or an explanation of why it does not
- [ ] This PR includes a **CHANGELOG entry** or does not need one
- [ ] The **UI tests** are passing after this PR (`./gradlew connectedAmazonWebViewDebugAndroidTest`)
- [ ] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: tools/sign_release.sh [hunk 1]
```diff
@@ -87,8 +71,18 @@ curl -F "input=@$BUILD_DIR/app-amazonWebview-release-unsigned.apk" \
 zipalign -v 4 $BUILD_DIR/$FINAL_NAME $BUILD_DIR/app-amazonWebview-release-aligned.apk
 mv -f $BUILD_DIR/app-amazonWebview-release-aligned.apk $BUILD_DIR/$FINAL_NAME
 
+
+# We don't use `-Werr` (treat warnings as errors) because errors related to certain AndroidX
+# files are expected here.
+#
+# When the build is signed by Autograph, files inside the META-INF folder are not signed (due to
```
Comment (mcomella) [inline tools/sign_release.sh]: Can we be specific about the outdated dependency? It's because they use jarsigner/apksigner v1 instead of v2, right?

File: tools/sign_release.sh [hunk 2]
```diff
@@ -87,8 +71,18 @@ curl -F "input=@$BUILD_DIR/app-amazonWebview-release-unsigned.apk" \
...
+# an outdated dependency on their end). We previously stripped these files out of the APK to
+# avoid warnings, but after migrating to AndroidX important files are now stored in this
+# directory (they appear to be Jetified libraries, but we haven't verified that). As we can't
+# strip these files out, we stop failing on warnings instead.
```
Comment (mcomella) [inline tools/sign_release.sh]: nit: can we file a bug to re-enable -Werr when autograph does the right thing and link to the issue number here?

Comment (Baron-Severin) [reply tools/sign_release.sh]: Opened https://github.com/mozilla-mobile/firefox-echo-show/issues/290
