### PR TITLE
Closes #75: Add pinch gesture to exit fullscreen mode

### LINKED ISSUE #75: Provide close fullscreen option if website fails to provide controls to exit fullscreen
https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/487

### PR DESCRIPTION
**Pull request by mcomella**
### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt [hunk 1]
```diff
@@ -71,6 +73,7 @@ object TelemetryWrapper {
         const val HOME_TILE = "home_tile"
         val TURBO_MODE = "turbo_mode"
         val PIN_PAGE = "pin_page"
+        const val FULLSCREEN = "fullscreen"
```
Comment (liuche) [inline app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt]: Data request form? :)

File: app/src/main/java/org/mozilla/focus/browser/FullscreenCallbacks.kt [hunk 2]
```diff
@@ -16,18 +16,26 @@ import kotlinx.android.synthetic.main.fragment_browser.*
...
+import org.mozilla.focus.widget.OnInterceptTouchEventFrameLayout
 
 /**
  * An [IWebView.Callback] that only handles the fullscreen related callbacks.
  */
-class FullscreenCallbacks(
-        private val browserFragment: BrowserFragment
+open class FullscreenCallbacks(
+    private val browserFragment: BrowserFragment,
+    private val telemetryWrapper: TelemetryWrapper = TelemetryWrapper
```
Comment (liuche) [inline app/src/main/java/org/mozilla/focus/browser/FullscreenCallbacks.kt]: Do we need to do this elsewhere for mocking, in tests? Is this something we need to add to avoid tests sending telemetry...?

Comment (mcomella) [reply app/src/main/java/org/mozilla/focus/browser/FullscreenCallbacks.kt]: In theory, anywhere we need to mock telemetry, we need to pass in the dependency so yes something like this. However, it's probably not worth refactoring all the code to pass in the telemetry dependency unless it's strictly needed.

wrt testing, I don't think manually passing in the telemetry dependency is a sustainable way to avoid sending tests during telemetry. I think we need a comprehensive rethink of our approaches. There's:
- robolectric: https://github.com/mozilla-mobile/firefox-tv/issues/1300 (which improbably sends events)
- A discussion thread: https://groups.google.com/a/mozilla.com/d/msg/android-product-team/BJADnmwk2V4/NOanXwIECgAJ
- This components issue: https://github.com/mozilla-mobile/android-components/issues/695
- This fenix issue: https://github.com/mozilla-mobile/fenix/issues/124
- An issue I just filed against glean: https://bugzilla.mozilla.org/show_bug.cgi?id=1514336

I'll bring it up in the original thread.

**Comment by mcomella** [comment]
@liuche

# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

- Do users use the pinch gesture to exit full screen?
- How often do users pinch-to-exit full screen rather than clicking the web application's UI?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

- Ensure users are aware of the pinch-to-exit gesture in case the web application locks them in fullscreen mode (intentionally or not)
- Ensure the gesture is useful and that we should maintain it instead of taking it out

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

- None: we're adding a new feature and, without strong UR support on this platform, it's hard to do more in-depth analyses and this should be an efficient way to understand how users interact with the device.

4) Can current instrumentation answer these questions?

No.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>ACTION, HIDE, FULLSCREEN, SCALE_GESTURE=true/false</td>
    <td>2 interaction</td>
    <td>#75</td>
  </tr>
</table>


6) How long will this data be collected?  Choose one of the following:

* I want to permanently monitor this data. (@athomasmoz )

7) What populations will you measure?

* Which release channels?
All

* Which countries?
All

* Which locales?
All

* Any other filters?  Please describe in detail below.

8) If this data collection is default on, what is the opt-out mechanism for users?

Opt-out in settings.

9) Please provide a general description of how you will analyze this data.

After feature is released, look at data to understand if users are using it, ensuring users are actually exiting fullscreen altogether before we jump to conclusions. If not, we may add better onboarding.

10) Where do you intend to share the results of your analysis?

- Internally, sql.tmo

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt (hunk 1 above)
Comment (mcomella) [reply app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt]: Done, thanks: https://github.com/mozilla-mobile/firefox-echo-show/pull/144#issuecomment-447521809

**Comment by liuche** [comment]
1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate?

Yes, documented in `telemetry.md`

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, firefox data controls

3) If the request is for permanent data collection, is there someone who will monitor the data over time?**

@athomasmoz will monitor

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **

Type 2

5) Is the data collection request for default-on or default-off?

default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No, interaction only

7) Is the data collection covered by the existing Firefox privacy notice?

Yes, interaction with UI

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**

Will review during bulk Mobile telemetry review.
