### PR TITLE
Closes #297: Set default overlay visible value to false

### LINKED ISSUE #297: Toolbar does not scroll off-screen on first page load after session restoration
## Steps to reproduce
- Make sure a page is ready to be restored
  - "Echo, open Firefox"
  - Navigate to page (e.g. WIkipedia)
  - Click a link
  - "Echo, go home"
  - `adb shell am force-stop org.mozilla.connect.firefox` or wait for timeout
- "Echo, open Firefox"
  - Verify page is restored. If following the instructions above, the last loaded page will be loaded and there will be no back stack
- Scroll page around

### Expected behavior
Toolbar moves on and off screen

### Actual behavior
Toolbar stays on screen. **When the user fullscreens a video, the toolbar remains on the screen.** This state is fixed when the user:
- opens the navigation overlay (e.g. to load a new page)
- loads a url via the url bar

But clicking links to load new pages doesn't fix the issue. This is problematic if they user starts on YouTube and only clicks on links in YouTube to navigate.

This problem is pronounced on the ES gen 5 because of its small screen and will combine with our solutions to #284 to be even worse.

### Device information
* Echo Show device (1st gen, 2nd gen, or 5): verified on 5; probably affects all of them
* Latest affected Firefox version: up/master ef4acaf3
* Earliest affected Firefox version: ?

---

My assumption is that we set an initial toolbar state (canScroll = false) when starting the app on the Navigation Overlay. However, when we implemented session restore, we never updated this state.

If it helps, I changed the code in BrowserAppBarViewModel to this:
```kotlin
    val isAppBarHidden = MutableLiveData<Boolean>().apply {
        value = true
    }
```

And it seemed to fix the issue, sort of. It's not the right fix but maybe it'll help debugging.

### PR DESCRIPTION
**Pull request by dnarcese**
On session restore, the `isToolbarScrollEnabled` value was not set correctly to true because the overlay was not visited first, and that is when the value changes. Setting `isNavigationOverlayVisible` default to false is the fix.
### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
- [x] This PR includes a **CHANGELOG entry** or does not need one
- [x] The **UI tests** are passing after this PR (`./gradlew connectedAmazonWebViewDebugAndroidTest`)
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/toolbar/BrowserAppBarViewModel.kt [hunk 1]
```diff
@@ -20,7 +20,9 @@ class BrowserAppBarViewModel(
     sessionRepo: SessionRepo
 ) : ViewModel() {
 
-    private val isNavigationOverlayVisible = MutableLiveData<Boolean>()
+    private val isNavigationOverlayVisible = MutableLiveData<Boolean>().apply {
+        value = false
```
Comment (mcomella) [inline app/src/main/java/org/mozilla/focus/toolbar/BrowserAppBarViewModel.kt]: nit: We should add a comment to explain why this is false by default. The two important points are:
- this value changes in response to the navigation overlay changing visibility
- The navigation overlay is hidden by default, particularly in the case of session restore

**Comment by mcomella** [comment]
It looks like lint failed. Severin made partial progress in this PR: https://github.com/mozilla-mobile/firefox-echo-show/pull/291

I'll take a look at the errors and, assuming this PR doesn't change anything, I think I can just force-merge it.

**Comment by mcomella** [comment]
@dnarcese I noticed you didn't complete the checklist items. In particular, we have no UI tests on CI so can you make sure to run them locally?
