### PR TITLE
Closes #218: Set WebView background color to white.

### LINKED ISSUE #218: Screen flickers after navigating away from home page either on first use or after clearing data
## Steps to reproduce
1. Open Firefox
2. If first time use:
- Click on a default tile such as Wikipedia OR
- Click on URL, enter URL and go OR
- Click on Settings then About
3. If not first time use:
- Go to settings and clear data
- Go to home page
- Click on a default tile such as Wikipedia OR
- Click on URL, enter URL and go OR
- Click on Settings then About
### Expected behavior
You will navigate to the new page in a manner that is visually similar to existing browser experiences
### Actual behavior
The screen will flicker and even appear to jerk up and down as it loads the new page
### Device information

* Echo Show device 2nd Gen
* Firefox version Latest Build (Says 1.2, but we call it 1.3)

### PR DESCRIPTION
**Pull request by mcomella**
kglazko confirmed that the speculative fix is working.

### Pull Request checklist

- [x] This PR includes thorough **tests** or an explanation of why it does not
  - In order to test this, I think we'd need to run an integration test on the device that had the issue and verify that `backgroundColor` is set to white (assuming `backgroundColor` would return something different on that device). This doesn't seem like a useful test because it requires such specific hardware and comes at such a high cost
- [x] This PR includes a **CHANGELOG entry** or does not need one
  - Never introduced to users
- [x] The **UI tests** are passing after this PR (`./gradlew connectedAmazonWebViewDebugAndroidTest`)
- [x] I have considered adding **QA labels** on the associated issue (not this PR; `qa-ready` or `qa-denied`)

### CODE REVIEW

File: app/src/amazonWebview/java/org/mozilla/focus/webview/FirefoxWebView.kt [hunk 1]
```diff
@@ -48,6 +49,17 @@ internal class FirefoxWebView(
...
         setOnLongClickListener(linkHandler)
         isLongClickable = true
+        initBackgroundColor()
+    }
+
+    private fun initBackgroundColor() {
+        // The initial navigation overlay is drawn over the WebView. However, on some Echo Show devices [1], the
+        // overlay fade out animation causes graphical glitches, as if the WebView's background color is transparent
+        // (graphical glitches usually occur when parts of the screen have no draw calls on them). We speculatively
+        // fixed this issue by overriding to an opaque default color.
```
Comment (Baron-Severin) [inline app/src/amazonWebview/java/org/mozilla/focus/webview/FirefoxWebView.kt]: Since MTV verified this works, the fix isn't speculative anymore.  Suggest updating that sentence.

**Comment by mcomella** [comment]
@Baron-Severin Very interesting: this patch _increases_ code coverage, presumably because some test inits a FirefoxWebView. This can be even more misleading than I had assumed, it seems. :)
